nome = input('Olá, qual o seu nome? ')
print('Prazer em te conhecer', nome)
idade = input('Qual a sua idade? ')
dia = input('Em qual dia você nasceu? ')
mes = input('Em que mês você nasceu? ')
ano = input('Em que ano vcê nasceu? ')
print(nome, 'nasceu no dia', dia, 'do mês', mes, 'no ano de', ano)